### ISSUE TITLE
2. C výsledný katalóg požiadaviek

### ISSUE THREAD

**Issue by matus01** [TIS2022-FMFI/medical-examinations#5]
Výsledný katalóg požiadaviek, ktorý odsúhlasil zadávateľ. Kým mal zadávateľ pripomienky, treba ich najskôr zohľadniť a ponúknuť mu na odsúhlasenie aktualizovanú, vylepšenú verziu. Pred tým, ako sa posiela návrh katalógu požiadaviek zadávateľovi, ho musí schváliť cvičiaci.

**Comment by pavelpetrovic** [comment]
par komentarov v dokumente
[katalog_poziadaviek_s_komentarmi.docx](https://github.com/TIS2022-FMFI/medical-examinations/files/9814569/katalog_poziadaviek_s_komentarmi.docx)

**Comment by pavelpetrovic** [comment]
prosim porovnat posledne dve verzie cez document compare, aby bolo farbne oznacene a poslat v takej verzii zadavatelovi, ze ci tieto navrhy uprav od cviciaceho su akceptovatelne.
